module.exports = [
  {isPaid: true, userId: 1, date: Date.now()},
  {isPaid: true, userId: 2, date: Date.now()},
  {isPaid: true, userId: 3, date: Date.now()},
  {isPaid: true, userId: 4, date: Date.now()},
  {isPaid: true, userId: 5, date: Date.now()},
  {isPaid: true, userId: 6, date: Date.now()},
  {isPaid: true, userId: 7, date: Date.now()},
  {isPaid: true, userId: 8, date: Date.now()},
  {isPaid: true, userId: 9, date: Date.now()},
  {isPaid: true, userId: 10, date: Date.now()},
  {isPaid: false, userId: 1, date: null},
  {isPaid: false, userId: 2, date: null},
  {isPaid: false, userId: 3, date: null},
  {isPaid: false, userId: 4, date: null},
  {isPaid: false, userId: 5, date: null},
  {isPaid: false, userId: 6, date: null},
  {isPaid: false, userId: 7, date: null},
  {isPaid: false, userId: 8, date: null},
  {isPaid: false, userId: 9, date: null},
  {isPaid: false, userId: 10, date: null}
]
